FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV WEBHOOK_URL=https://n8n-render-deploy-lzqt.onrender.com
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true


EXPOSE 5678

CMD ["n8n"]
